#!/bin/bash

julia_img=`ls /opt/browncis/containers/bcbi/sh-julia-datasci-bio`

len=${#julia_img[*]}

if (( $len == 1))
then
    echo "**********************************************************************"
    echo "Running $julia_img "
    echo "**********************************************************************"
    singularity exec -B /run -B /data $julia_img julia "$@"
else
    echo "**********************************************************************"
    echo "Error - more than one julia image found ($len). Contact addministrator"
    echo "**********************************************************************"
fi
