#!/bin/bash

COMMAND="/opt/public_mm/bin/skrmedpostctl start && /opt/public_mm/bin/wsdserverctl start && /opt/public_mm/bin/metamap "$@""

metamap_image="/opt/browncis/containers/bcbi/metamap-2018.simg"

mkdir -p $HOME/.metamap/tagger_log
mkdir -p $HOME/.metamap/wsd_log

echo "**********************************************************************"
echo "Running metamap image $metamap_image "
echo "with options "$@""
echo "**********************************************************************"

TAGGER_LOG=~/.metamap/tagger_log:/opt/public_mm/MedPost-SKR/Tagger_server/log
WSD_LOG=~/.metamap/wsd_log:/opt/public_mm/WSD_Server/log

singularity exec --cleanenv -B /data -B $TAGGER_LOG -B $WSD_LOG  $metamap_image bash -c "${COMMAND}"